language: python
python:
 - "2.7"
# command to install dependencies
install:
 - pip install pytest pytest-cov
 - pip install mockito
 - pip install coveralls
 - pip install pep8
 - pip install radon
# command to run tests
script:
 - py.test --cov . --cov-report term-missing
 - radon cc src/Empresa.py -a -nc
 - radon raw src/Empresa.py -a -nc
 - radon mi src/Empresa.py -a -nc
after_success:
 - coveralls
 - radon cc src/Empresa.py -a -nc
 - radon raw src/Empresa.py -a -nc
 - radon mi src/Empresa.py -a -nc
