language: python
python:
 - "2.7"
# command to install dependencies
install:
 - pip install pytest pytest-cov
 - pip install mockito
 - pip install coveralls
 - pip install pep8
 - pip install radon
# command to run tests
script:
 - py.test --cov . --cov-report term-missing
 - radon cc -s -a -e src/Empresa.py
 - radon raw -s -a -e src/Empresa.py
 - radon mi -s -a -e src/Empresa.py
after_success:
 - coveralls
 - radon cc -s -a -e src/Empresa.py
 - radon raw -s -a -e src/Empresa.py
 - radon mi -s -a -e src/Empresa.py
